name: Ruff Lint

on:
  push:
    branches: [main, "**"]  # Run on all pushes, including branches
  pull_request:             # Run on all PRs

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Run Ruff
        run: ruff check .
